services:
  - type: web
    name: icloud-importer-backend
    env: python
    rootDir: .
    buildCommand: |
      python --version
      pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: CORS_ORIGINS
        value: https://import-icloud-frontend.vercel.app/
      - key: FIREBASE_CREDENTIALS
        sync: false 